title: Isaac Muro
author: Isaac Muro
email: img@disroot.org
description: > # this means to ignore newlines until "baseurl:"
  M'autogestiono quan puc. La meva pàgina personal per reunir moltes coses disperses per internet,
  que poc a poc aniré reunint aquí, per tenir-les també al meu ordinador.
  Pàgina creada amb jekyll i gitlab pages.
source_code: https://gitlab.com/isaacmg/isaacmg.gitlab.io
twitter_username: willezumleben
gitlab_username:  isaacmg
paginate: 5
paginate_path: "/blog/page:num/"
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate

disqus.shortname: isaacmg-gitlab-io

permalink: /blog/:year/:month/:day/:title
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
