title: Isaac Muro
author: Isaac Muro
email: imuro3@xtec.cat
description: > # this means to ignore newlines until "baseurl:"
  La meva pàgina personal per reunir moltes coses disperses per internet,
  que poc a poc aniré reunint aquí, per tenir-les també al meu ordinador.
  Pàgina creada amb jekyll i github pages. Podeu trobar el codi font de tota
  la pàgina al meu github!

twitter_username: willezumleben
github_username:  isaacmuro
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-sitemap
  - jekyll-paginate
site.disqus.shortname:https://isaacmuro-github-io
permalink: /blog/:year/:month/:day/:title
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
